### ISSUE TITLE
When I was dragging somthing,right-click will triggered!

### ISSUE THREAD

**Issue by janryWang** [vkbansal/react-contextmenu#52] opened 2016-12-01 09:44 UTC
## Version
2.0.0-alpha.2

## Test Case
http://jsbin.com/lixucamice/1/edit?js,output

**Comment by janryWang** [comment] 2016-12-01 09:49
This problem does not always occur, it only occasionally appears

**Comment by vkbansal** [comment] 2016-12-02 13:11
duplicate of #47

**Closed by vkbansal** 2016-12-02 13:11 UTC
