### ISSUE TITLE
ContextMenu position is not correct when using css transform.

### ISSUE THREAD

**Issue by ZachLiuGIS** [vkbansal/react-contextmenu#158] opened 2017-10-03 01:51 UTC
I was trying to use react-contextmenu in out app, then I found the context menu position is misplaced. I did some research and found that it is because of if your parent node has css transform, it will create new stacking context and the event x and y will not be correct.

Here is my reproducing the bug,
[](https://codesandbox.io/s/3q14z0y631)

Here is the stackoverflow issue about css fixed position
[](https://stackoverflow.com/questions/15194313/transform3d-not-working-with-position-fixed-children/15256339#15256339)

I found similar issue from another context-menu package
[](https://github.com/fkhadra/react-contexify/issues/27)

I think they are waiting for React v16's createPortal to fix it. 

Another fix may be by creating an dom element in ContextMenu and use document.body.appendChild(element) to get a node outside of its parent. Then when ContextMenu is updated, call ReactDOM.render(React.cloneElement(ContextMenu.children), this.ref(Element)).

**Comment by vkbansal** [comment] 2017-10-03 05:14
duplicate of #147

**Comment by vkbansal** [comment] 2017-10-04 07:08
> if your parent node has css transform, it will create new stacking context and the event x and y will not be correct.

If event x and y are itself incorrect, then even portal will not help

**Closed** 2017-12-10 07:39 UTC
Labels: wontfix
