### ISSUE TITLE
Prevent menu to show up after fire dragStart. 

### ISSUE THREAD

**Issue by robert8888** [vkbansal/react-contextmenu#321] opened 2020-03-30 20:50 UTC
## Actual Behavior

When dragStart is fired menu shows up after value setted to holdToDisplay. Yes you can set holdToDisplay on -1 but still is not desire behavior. 

Best

**Comment by vkbansal** [comment] 2020-03-31 09:08
This is intended behaviour. Changing this will make it stop working on touch screen devices.

**Comment by robert8888** [comment] 2020-06-02 08:03
Ok. I get this point of view, but still i suppose that you can catch drag start / drag end on the root (eg. body) element  (it is bubbling in most case) and then don't show menu during dragging.

Best.

**Comment by vkbansal** [comment] 2020-06-03 11:01
I'm not too familiar with how things work on touch devices. Can you share a code sample of what you are proposing? Even better if you code provide a PR.

**Comment by vkbansal** [comment] 2020-08-11 04:34
closing issue see #339

**Closed by vkbansal** 2020-08-11 04:34 UTC
